# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\Programs\mingw64\bin\cmake.exe

# The command to remove a file.
RM = D:\Programs\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "D:\WangCJ\Codes\Dev Codes\OITools\Source-Wrapper"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "D:\WangCJ\Codes\Dev Codes\OITools\Source-Wrapper"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	D:\Programs\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	D:\Programs\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	D:\Programs\mingw64\bin\cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	D:\Programs\mingw64\bin\cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	D:\Programs\mingw64\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	D:\Programs\mingw64\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	D:\Programs\mingw64\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	D:\Programs\mingw64\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\WangCJ\Codes\Dev Codes\OITools\Source-Wrapper\CMakeFiles" "D:\WangCJ\Codes\Dev Codes\OITools\Source-Wrapper\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\WangCJ\Codes\Dev Codes\OITools\Source-Wrapper\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named oit-wrap

# Build rule for target.
oit-wrap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 oit-wrap
.PHONY : oit-wrap

# fast build rule for target.
oit-wrap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-wrap.dir\build.make CMakeFiles/oit-wrap.dir/build
.PHONY : oit-wrap/fast

src/info.obj: src/info.cpp.obj
.PHONY : src/info.obj

# target to build an object file
src/info.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-wrap.dir\build.make CMakeFiles/oit-wrap.dir/src/info.cpp.obj
.PHONY : src/info.cpp.obj

src/info.i: src/info.cpp.i
.PHONY : src/info.i

# target to preprocess a source file
src/info.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-wrap.dir\build.make CMakeFiles/oit-wrap.dir/src/info.cpp.i
.PHONY : src/info.cpp.i

src/info.s: src/info.cpp.s
.PHONY : src/info.s

# target to generate assembly for a file
src/info.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-wrap.dir\build.make CMakeFiles/oit-wrap.dir/src/info.cpp.s
.PHONY : src/info.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-wrap.dir\build.make CMakeFiles/oit-wrap.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-wrap.dir\build.make CMakeFiles/oit-wrap.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-wrap.dir\build.make CMakeFiles/oit-wrap.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/options.obj: src/options.cpp.obj
.PHONY : src/options.obj

# target to build an object file
src/options.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-wrap.dir\build.make CMakeFiles/oit-wrap.dir/src/options.cpp.obj
.PHONY : src/options.cpp.obj

src/options.i: src/options.cpp.i
.PHONY : src/options.i

# target to preprocess a source file
src/options.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-wrap.dir\build.make CMakeFiles/oit-wrap.dir/src/options.cpp.i
.PHONY : src/options.cpp.i

src/options.s: src/options.cpp.s
.PHONY : src/options.s

# target to generate assembly for a file
src/options.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\oit-wrap.dir\build.make CMakeFiles/oit-wrap.dir/src/options.cpp.s
.PHONY : src/options.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... oit-wrap
	@echo ... src/info.obj
	@echo ... src/info.i
	@echo ... src/info.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/options.obj
	@echo ... src/options.i
	@echo ... src/options.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

